name: build

on:
  push:
    branches: [ $default-branch ]
    paths:
      - '**.cs'
  pull_request:
    paths:
      - '**.cs'
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build Mod
        uses: KSPModStewards/KSPCommon/.github/workflows/build@main
