name: build

on:
  push:
    branches: [ $default-branch ]
    paths:
      - '**.cs'
  pull_request:
    paths:
      - '**.cs'
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    uses: KSPModdingLibs/KSPBuildTools/.github/workflows/build.yml@main
    with:
      artifacts: |
        GameData
        LICENSE.md
    secrets:
      ksp-zip-password: ${{ secrets.KSP_ZIP_PASSWORD }}
      
