name: update-version

on:
  workflow_dispatch:
    inputs:
      version-string:
        type: string

jobs:
  update-version:
    uses: KSPModdingLibs/KSPBuildTools/.github/workflows/update-version.yml@main
    with:
      version-string: ${{inputs.version-string}}
